### ISSUE TITLE
Add ScreenOverlay support

### ISSUE THREAD

**Issue by IanLee1521** [cleder/fastkml#18]
https://developers.google.com/kml/documentation/kmlreference#screenoverlay

**Comment by heltonbiker** [comment]
Is there any coding standard for this? Would it be enough to (more or less) follow the structure of `ImageOverlay` class?

**Comment by cleder** [comment]
I do not know if this is used anymore now that google earth is dead. Is there any other client that uses this?

**Comment by heltonbiker** [comment]
@cleder, that's a point. I see two main possibilities:

1. The purist approach: consider that KML, being an OGC standard, "deserves" a canonical implementation, disregarding the existence or not of applications actually using the full set of elements;
2. The pragmatic approach: given the constraints (time, effort, personal involvement), it would be much better to implement other, more useful features before "wasting time" with the underused ScreenOverlay element.

As such, the question follows: is there any other obvious condidate Element to implement next, instead of ScreenOverlay?

**Comment by cleder** [comment]
CesiumJs uses the gx extensions like flyTo, etc

**Comment by cleder** [comment]
https://bitbucket.org/sbarbot/sceq/raw/default/sceq.kml is an example of screen overlay

**Comment by heltonbiker** [comment]
Nice!

As a curiosity, since Marble is configured in this machine to open KML by
default, I could notice that currently it _doesn't_ implement screen
overlay.

See ya!

Helton

2016-05-05 5:55 GMT-03:00 Christian Ledermann <notifications@github.com>:

**Comment by cleder** [comment]
Closing this, in ten years there was no other request for this.

**Comment by cleder** [comment]
https://github.com/cleder/fastkml/blob/develop/tests/ogc_conformance/data/kml/KML_Samples.kml#L360

**Comment by cleder** [comment]
```xml
<complexType name="ScreenOverlayType" final="#all">
    <complexContent>
      <extension base="kml:AbstractOverlayType">
        <sequence>
          <element ref="kml:overlayXY" minOccurs="0"/>
          <element ref="kml:screenXY" minOccurs="0"/>
          <element ref="kml:rotationXY" minOccurs="0"/>
          <element ref="kml:size" minOccurs="0"/>
          <element ref="kml:rotation" minOccurs="0"/>
          <element ref="kml:ScreenOverlaySimpleExtensionGroup" minOccurs="0"
            maxOccurs="unbounded"/>
          <element ref="kml:ScreenOverlayObjectExtensionGroup" minOccurs="0"
            maxOccurs="unbounded"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
```
